import * as path from 'path';
import { STANDARD_UNITS } from './tokenizer';

const UNIT_SET = new Set(STANDARD_UNITS);

/**
 * Checks whether a line of PHS code contains a variable assignment operator (`=`).
 * Excludes equality comparisons (`==`), unit conversions (`=>`), and inequality operators.
 */
function isAssignmentLine(code: string): boolean {
    return /(?<![=>!<])=(?![=>=])/u.test(code);
}

/**
 * Checks whether the word following a numeric literal is a valid physical unit.
 */
function isUnitStart(word: string): boolean {
    const cleanWord = word.replace(/[^a-zA-Z\p{L}_]/gu, '');
    return UNIT_SET.has(cleanWord);
}

/**
 * Replaces quantity literals like `1.673e-27 kg` or `10 m +/- 0.5 m` in an PHS
 * expression string with native Python `Q_(val, "unit")` calls.
 */
function transformQuantityLiterals(expr: string): string {
    let result = expr;

    // 1. Transform uncertainty quantities: e.g. 10 m +/- 0.5 m OR 10 +/- 0.5 m
    const uncRegex = /(\b\d+\.?\d*(?:[eE][+-]?\d+)?\b)\s*([a-zA-Z\p{L}_⁰¹²³⁴⁵⁶⁷⁸⁹₀₁₂₃₄₅₆₇₈₉]+)?\s*(?:\+\/-|±)\s*(\d+\.?\d*(?:[eE][+-]?\d+)?\b)\s*([a-zA-Z\p{L}_⁰¹²³⁴⁵⁶⁷⁸⁹₀₁₂₃₄₅₆₇₈₉]+)?/gu;
    result = result.replace(uncRegex, (_, val, u1, unc, u2) => {
        const unitStr = (u1 || u2 || '').trim();
        if (unitStr) {
            return `Q_(${val}, "${unitStr}", ${unc})`;
        }
        return `Q_(${val}, "", ${unc})`;
    });

    // 2. Transform standard quantities: <number> <unit_expr>
    // Matches a number followed by whitespace and words/operators forming a unit expression.
    const numUnitRegex = /(\b\d+\.?\d*(?:[eE][+-]?\d+)?\b)\s+([a-zA-Z\p{L}_⁰¹²³⁴⁵⁶⁷⁸⁹₀₁₂₃₄₅₆₇₈₉]+(?:\s*(?:[\/*\^]|\*\*)\s*(?:\([^)]+\)|[a-zA-Z\p{L}_⁰¹²³⁴⁵⁶⁷⁸⁹₀₁₂₃₄₅₆₇₈₉\d]+))*)/gu;

    result = result.replace(numUnitRegex, (fullMatch, numStr, unitCandidate) => {
        const firstWord = unitCandidate.trim().split(/[\s\/*\^()]/)[0];
        if (isUnitStart(firstWord)) {
            return `Q_(${numStr}, "${unitCandidate.trim()}")`;
        }
        return fullMatch;
    });

    // 3. Convert caret exponent ^ and split asterisks * * to Python ** outside string quotes
    result = result.replace(/\*\s+\*/g, '**');

    let inQuotes = false;
    let pyCode = '';
    for (let i = 0; i < result.length; i++) {
        const ch = result[i];
        if (ch === '"' || ch === "'") {
            inQuotes = !inQuotes;
            pyCode += ch;
        } else if (ch === '^' && !inQuotes) {
            pyCode += '**';
        } else {
            pyCode += ch;
        }
    }

    return pyCode;
}

/**
 * Transpiles a single PHS code line or expression into native Python code.
 */
function transpileCodeLine(code: string): string {
    const trimmed = code.trim();
    if (!trimmed) {
        return '';
    }

    // 1. Check for format specifiers e.g. force_: frac|base OR expr: .2f
    const colonIdx = trimmed.lastIndexOf(':');
    if (colonIdx !== -1 && !trimmed.includes('(')) {
        const exprPart = trimmed.substring(0, colonIdx).trim();
        const specPart = trimmed.substring(colonIdx + 1).trim();
        if (specPart && !specPart.includes('=')) {
            const transformedExpr = transformQuantityLiterals(exprPart);
            return `f"{${transformedExpr}:${specPart}}"`;
        }
    }

    // 2. Check for unit conversion operators (=> or ->)
    const convMatch = /(.*?)\s*(?:=>|->)\s*(.*)/.exec(trimmed);
    if (convMatch) {
        const lhs = transformQuantityLiterals(convMatch[1].trim());
        const targetUnit = convMatch[2].trim();
        return `(${lhs}).to("${targetUnit}")`;
    }

    // 3. Standard expression transformation
    return transformQuantityLiterals(trimmed);
}

/**
 * Smartly transpiles PHS source code into clean, native Python code
 * using `Q_` and native Python constructs (functions, expressions, variables).
 */
export function transpiledPhsToPython(phsText: string): string {
    const lines = phsText.split(/\r\n|\r|\n/);
    const pythonLines: string[] = [
        '# Generated by Physure VS Code Extension',
        'from physure import Q_, Quantity',
        '',
    ];

    let i = 0;
    while (i < lines.length) {
        const rawLine = lines[i];
        const trimmed = rawLine.trim();

        // 1. Blank lines
        if (!trimmed) {
            pythonLines.push('');
            i++;
            continue;
        }

        // 2. Full line comments
        if (trimmed.startsWith('#')) {
            pythonLines.push(rawLine);
            i++;
            continue;
        }

        // 3. Display Text Blocks (``` ... ```) -> Python docstrings
        if (trimmed.startsWith('```')) {
            if (trimmed.length > 3 && trimmed.endsWith('```')) {
                const textContent = trimmed.substring(3, trimmed.length - 3);
                pythonLines.push(`"""${textContent}"""`);
                i++;
                continue;
            }

            const textLines: string[] = [];
            i++; // skip opening ```
            while (i < lines.length && !lines[i].trim().startsWith('```')) {
                textLines.push(lines[i]);
                i++;
            }
            if (i < lines.length && lines[i].trim().startsWith('```')) {
                i++; // skip closing ```
            }

            pythonLines.push('"""');
            pythonLines.push(...textLines);
            pythonLines.push('"""');
            continue;
        }

        // 4. Multiline or single-line Function Definition: f(params) =
        const funcHeaderMatch = /^([\p{L}_][\p{L}\p{N}_]*)\s*\(([^)]*)\)\s*=(?!=)/u.exec(trimmed);
        if (funcHeaderMatch) {
            const funcName = funcHeaderMatch[1];
            const rawParams = funcHeaderMatch[2];

            const paramList = rawParams
                .split(',')
                .map((p) => {
                    const parts = p.split(':');
                    return {
                        name: parts[0].trim(),
                        unit: parts[1] ? parts[1].trim() : undefined,
                    };
                })
                .filter((p) => p.name.length > 0);

            const cleanParamsStr = paramList.map((p) => p.name).join(', ');
            pythonLines.push(`def ${funcName}(${cleanParamsStr}):`);

            // Inject runtime unit conversion / safety checks for annotated parameters
            for (const param of paramList) {
                if (param.unit) {
                    pythonLines.push(`    ${param.name} = ${param.name}.to("${param.unit}")`);
                }
            }

            // Collect function body lines
            const bodyLines: { line: string; indentStr: string }[] = [];
            i++;
            while (i < lines.length) {
                const nextLine = lines[i];
                const nextTrimmed = nextLine.trim();
                if (!nextTrimmed) {
                    i++;
                    continue;
                }
                const indent = nextLine.length - nextLine.trimStart().length;
                if (indent > 0) {
                    bodyLines.push({ line: nextTrimmed, indentStr: ' '.repeat(indent) });
                    i++;
                } else {
                    break;
                }
            }

            if (bodyLines.length === 0) {
                if (paramList.every((p) => !p.unit)) {
                    pythonLines.push('    pass');
                }
            } else {
                for (let bIdx = 0; bIdx < bodyLines.length; bIdx++) {
                    const isLast = bIdx === bodyLines.length - 1;
                    const { line: bLine, indentStr } = bodyLines[bIdx];
                    const transformedBody = transpileCodeLine(bLine);

                    if (isLast && !isAssignmentLine(bLine)) {
                        pythonLines.push(`${indentStr}return ${transformedBody}`);
                    } else {
                        pythonLines.push(`${indentStr}${transformedBody}`);
                    }
                }
            }
            continue;
        }

        // 5. Single line statements / assignments / expressions
        const commentIdx = rawLine.indexOf('#');
        const codePart = commentIdx !== -1 ? rawLine.substring(0, commentIdx).trimEnd() : rawLine;
        const commentPart = commentIdx !== -1 ? rawLine.substring(commentIdx) : '';

        const trimmedCode = codePart.trim();
        const indentStr = rawLine.substring(0, rawLine.length - rawLine.trimStart().length);

        if (!trimmedCode) {
            pythonLines.push(rawLine);
            i++;
            continue;
        }

        const transpiledCode = transpileCodeLine(trimmedCode);
        let pyStmt: string;

        if (isAssignmentLine(trimmedCode)) {
            pyStmt = `${indentStr}${transpiledCode}`;
        } else {
            pyStmt = `${indentStr}print(${transpiledCode})`;
        }

        if (commentPart) {
            pyStmt += `  ${commentPart}`;
        }

        pythonLines.push(pyStmt);
        i++;
    }

    return pythonLines.join('\n');
}

/**
 * Generates a clean Markdown report template from PHS source.
 * Pure function independent of VS Code API.
 */
export function phsToMarkdownReport(fileName: string, phsText: string): string {
    const lines = phsText.split(/\r\n|\r|\n/);
    const mdLines: string[] = [
        `# Physure Calculation Report: ${path.basename(fileName)}`,
        `*Generated on ${new Date().toLocaleDateString()}*`,
        '',
        '## Source Code & Expressions',
        '```phs',
        phsText,
        '```',
        '',
        '## Summary of Calculations',
        '| Line | Expression / Variable |',
        '| --- | --- |',
    ];

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i].trim();
        if (line && !line.startsWith('#') && !line.startsWith('```')) {
            const safeLine = line.replace(/\|/g, '\\|');
            mdLines.push(`| ${i + 1} | \`${safeLine}\` |`);
        }
    }

    mdLines.push('');
    return mdLines.join('\n');
}
