import * as vscode from 'vscode';

export type Language = 'en' | 'es';

export interface Translations {
    reportTitle: string;
    subTitle: string;
    academicTag: string;
    autoGenerated: string;
    secVariables: string;
    secSequence: string;
    symbol: string;
    location: string;
    evaluatedValue: string;
    noVariables: string;
    noExpressions: string;
    line: string;
    lines: string;
    figure: string;
    figCaptionPrefix: string;
    figCaptionSuffix: string;
    definition: string;
    exportReport: string;
    printPdf: string;
    themeToggle: string;
}

const DICTIONARY: Record<Language, Translations> = {
    en: {
        reportTitle: 'Physure Technical Report',
        subTitle: 'Physure Computational Report',
        academicTag: 'Academic Report',
        autoGenerated: 'Automatically generated by Physure Engine',
        secVariables: '1. Summary of Variables & Quantities',
        secSequence: '2. Calculation Sequence & Expressions',
        symbol: 'Symbol',
        location: 'Location',
        evaluatedValue: 'Evaluated Value',
        noVariables: 'No variable assignments registered.',
        noExpressions: 'No evaluated expressions detected.',
        line: 'Line',
        lines: 'Lines',
        figure: 'Figure',
        figCaptionPrefix: 'Graphical representation generated from',
        figCaptionSuffix: '',
        definition: 'Definition',
        exportReport: '📥 Export Report',
        printPdf: '🖨️ Print / PDF',
        themeToggle: '🌓 Theme',
    },
    es: {
        reportTitle: 'Informe Técnico Physure',
        subTitle: 'Physure Computational Report',
        academicTag: 'Reporte Académico',
        autoGenerated: 'Generado automáticamente por Physure Engine',
        secVariables: '1. Resumen de Variables y Magnitudes',
        secSequence: '2. Secuencia de Cálculos y Expresiones',
        symbol: 'Símbolo',
        location: 'Ubicación',
        evaluatedValue: 'Valor Evaluado',
        noVariables: 'No se registraron asignaciones de variables.',
        noExpressions: 'No se detectaron expresiones evaluadas.',
        line: 'Línea',
        lines: 'Líneas',
        figure: 'Figura',
        figCaptionPrefix: 'Representación gráfica generada a partir de',
        figCaptionSuffix: '',
        definition: 'Definición',
        exportReport: '📥 Exportar Reporte',
        printPdf: '🖨️ Imprimir / PDF',
        themeToggle: '🌓 Tema',
    },
};

export function getLanguage(documentUri?: vscode.Uri): Language {
    const config = vscode.workspace.getConfiguration('vsc-physure', documentUri);
    const lang = config.get<string>('language', 'en');
    return lang === 'es' ? 'es' : 'en';
}

export function getI18n(documentUri?: vscode.Uri): Translations {
    const lang = getLanguage(documentUri);
    return DICTIONARY[lang];
}
